package com.medicalappointment.controllers;

import com.medicalappointment.models.Medecin;
import com.medicalappointment.service.IMedecinService;
import com.medicalappointment.service.exception.ServiceException;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.*;

import java.util.List;
import java.util.stream.Collectors;

public class MedecinController extends BaseController {

    @FXML
    private TextField nomField;
    @FXML
    private TextField prenomField;
    @FXML
    private TextField specialiteField;
    @FXML
    private TextField numeroLicenceField;
    @FXML
    private TextField searchField;
    @FXML
    private TableView<Medecin> medecinTable;
    @FXML
    private TableColumn<Medecin, Integer> idColumn;
    @FXML
    private TableColumn<Medecin, String> nomColumn;
    @FXML
    private TableColumn<Medecin, String> prenomColumn;
    @FXML
    private TableColumn<Medecin, String> specialiteColumn;
    @FXML
    private TableColumn<Medecin, String> numeroLicenceColumn;

    private IMedecinService medecinService;
    private ObservableList<Medecin> medecinList;

    // Constructor for dependency injection
    public MedecinController(IMedecinService medecinService) {
        this.medecinService = medecinService;
    }

    // Default constructor for FXMLLoader
    public MedecinController() {
        try {
            this.medecinService = new com.medicalappointment.service.MedecinServiceImpl(
                new com.medicalappointment.models.dao.MedecinDAOImpl(
                    com.medicalappointment.models.dao.DatabaseConnectionManager.getInstance()
                )
            );
        } catch (Exception e) {
            e.printStackTrace();
            // Optionally, show an alert or log the error
        }
    }    @FXML
    public void initialize() {
        // Initialize table columns with explicit cell value factories
        idColumn.setCellValueFactory(cellData -> {
            Integer id = cellData.getValue().getId();
            return new javafx.beans.property.SimpleIntegerProperty(id).asObject();
        });
        
        nomColumn.setCellValueFactory(cellData -> {
            String nom = cellData.getValue().getNom();
            return new javafx.beans.property.SimpleStringProperty(nom);
        });
        
        prenomColumn.setCellValueFactory(cellData -> {
            String prenom = cellData.getValue().getPrenom();
            return new javafx.beans.property.SimpleStringProperty(prenom);
        });
        
        specialiteColumn.setCellValueFactory(cellData -> {
            String specialite = cellData.getValue().getSpecialite();
            return new javafx.beans.property.SimpleStringProperty(specialite);
        });
        
        numeroLicenceColumn.setCellValueFactory(cellData -> {
            String numeroLicence = cellData.getValue().getNumeroLicence();
            return new javafx.beans.property.SimpleStringProperty(numeroLicence);
        });

        medecinList = FXCollections.observableArrayList();
        medecinTable.setItems(medecinList);

        loadMedecins();

        medecinTable.getSelectionModel().selectedItemProperty().addListener(
                (observable, oldValue, newValue) -> showMedecinDetails(newValue));
    }    private void loadMedecins() {
        try {
            medecinList.clear();
            List<Medecin> medecins = medecinService.getAllMedecins();
            medecinList.addAll(medecins);
            
            // Force table refresh
            medecinTable.refresh();
        } catch (ServiceException e) {
            showAlert(Alert.AlertType.ERROR, "Error", "Failed to load medecins: " + e.getMessage());
        }
    }

    private void showMedecinDetails(Medecin medecin) {
        if (medecin != null) {
            nomField.setText(medecin.getNom());
            prenomField.setText(medecin.getPrenom());
            specialiteField.setText(medecin.getSpecialite());
            numeroLicenceField.setText(medecin.getNumeroLicence());
        } else {
            clearFields();
        }
    }    @FXML
    private void handleAddMedecin() {
        try {
            Medecin newMedecin = new Medecin(
                    0, // ID will be generated by DB
                    nomField.getText(),
                    prenomField.getText(),
                    specialiteField.getText(),
                    numeroLicenceField.getText()
            );
            medecinService.addMedecin(newMedecin);
            showAlert(Alert.AlertType.INFORMATION, "Success", "Medecin added successfully!");
            loadMedecins();
            clearFields();
        } catch (ServiceException e) {
            showAlert(Alert.AlertType.ERROR, "Error", "Failed to add medecin: " + e.getMessage());
        }
    }

    @FXML
    private void handleUpdateMedecin() {
        Medecin selectedMedecin = medecinTable.getSelectionModel().getSelectedItem();
        if (selectedMedecin != null) {
            try {
                selectedMedecin.setNom(nomField.getText());
                selectedMedecin.setPrenom(prenomField.getText());
                selectedMedecin.setSpecialite(specialiteField.getText());
                selectedMedecin.setNumeroLicence(numeroLicenceField.getText());

                medecinService.updateMedecin(selectedMedecin);
                showAlert(Alert.AlertType.INFORMATION, "Success", "Medecin updated successfully!");
                loadMedecins();
                clearFields();
            } catch (ServiceException e) {
                showAlert(Alert.AlertType.ERROR, "Error", "Failed to update medecin: " + e.getMessage());
            }
        } else {
            showAlert(Alert.AlertType.WARNING, "No Selection", "Please select a medecin to update.");
        }
    }

    @FXML
    private void handleDeleteMedecin() {
        Medecin selectedMedecin = medecinTable.getSelectionModel().getSelectedItem();
        if (selectedMedecin != null) {
            try {
                medecinService.deleteMedecin(selectedMedecin.getId());
                showAlert(Alert.AlertType.INFORMATION, "Success", "Medecin deleted successfully!");
                loadMedecins();
                clearFields();
            } catch (ServiceException e) {
                showAlert(Alert.AlertType.ERROR, "Error", "Failed to delete medecin: " + e.getMessage());
            }
        } else {
            showAlert(Alert.AlertType.WARNING, "No Selection", "Please select a medecin to delete.");
        }
    }

    @FXML
    private void handleClearFields() {
        clearFields();
    }

    private void clearFields() {
        nomField.clear();
        prenomField.clear();
        specialiteField.clear();
        numeroLicenceField.clear();
        medecinTable.getSelectionModel().clearSelection();
    }

    /**
     * Handle search functionality for medecins
     */
    @FXML
    private void handleSearchMedecins() {
        String searchText = searchField.getText().trim();
        if (searchText.isEmpty()) {
            handleShowAllMedecins();
            return;
        }

        try {
            List<Medecin> allMedecins = medecinService.getAllMedecins();
            List<Medecin> filteredMedecins = allMedecins.stream()
                .filter(medecin -> 
                    medecin.getNom().toLowerCase().contains(searchText.toLowerCase()) ||
                    medecin.getPrenom().toLowerCase().contains(searchText.toLowerCase()) ||
                    medecin.getSpecialite().toLowerCase().contains(searchText.toLowerCase()) ||
                    medecin.getNumeroLicence().toLowerCase().contains(searchText.toLowerCase())
                )
                .collect(Collectors.toList());
            
            medecinList.clear();
            medecinList.addAll(filteredMedecins);
            
            if (filteredMedecins.isEmpty()) {
                showAlert(Alert.AlertType.INFORMATION, "Résultats de recherche", 
                    "Aucun médecin trouvé pour \"" + searchText + "\"");
            }
        } catch (ServiceException e) {
            showAlert(Alert.AlertType.ERROR, "Error", "Failed to search medecins: " + e.getMessage());
        }
    }

    /**
     * Show all medecins (clear search filter)
     */
    @FXML
    private void handleShowAllMedecins() {
        searchField.clear();
        loadMedecins();
    }

    @FXML
    private void handleBackToMain(ActionEvent event) {
        loadView("/com/medicalappointment/views/main_view.fxml", "Medical Appointment Management", event.getSource());
    }    @Override
    protected void showAlert(Alert.AlertType alertType, String title, String message) {
        Alert alert = new Alert(alertType);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}


